version: '3.5'

services:
  aspnetcore_api:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    image: docker.pkg.github.com/trakx/data-market/trakx-data-market-server:latest
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SqlServerConnection=Server=sqlserver;Database=data_market;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=(@REPLACE_WITH_SQL_PASSWORD);Integrated Security=false
      - ApiKeys__CryptoCompare=abcd1234567890
    networks:
      - marketdata
    restart: always

  sqlserver:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - SA_PASSWORD=(@REPLACE_WITH_SQL_PASSWORD)
      - ACCEPT_EULA=Y
    ports:
      - 1533:1433 #expose port, so can connect to it using host: 'localhost,1533' | user: sa, password: oh_no_this-needs_toChange4Real
    networks:
      - marketdata
    restart: always

  proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - marketdata        
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - aspnetcore_api
    restart: always

volumes:
  sqlvolume:

networks:
  marketdata:
    name: marketdata_network
    ipam:
      driver: default
