version: '3.5'

services:
  marketdata_api:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    #image: docker.pkg.github.com/trakx/trakx-tools/trakx-marketdata-server:latest
    build:
      context: ./..
      dockerfile: ./src/Server.Dockerfile
    links:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Consider changing this in Production
      - ConnectionStrings__SqlServerConnection=Server=sqlserver;Database=IndiceRepository;Trusted_Connection=True;MultipleActiveResultSets=true;User=SA;Password=Ch@ngeMe123;Integrated Security=false
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=False
      - CRYPTOCOMPARE_API_KEY=xxx
    networks:
      - marketdata
    ports: 
      - "5000:5100"
    restart: always

  indexmanager_api:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    #image: docker.pkg.github.com/trakx/trakx-tools/trakx-indicemanager-server:latest
    build:
      context: ./..
      dockerfile: ./src/IndexManagerServer.Dockerfile
    links:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Consider changing this in Production
      - ConnectionStrings__SqlServerConnection=Server=sqlserver;Database=IndiceRepository;Trusted_Connection=True;MultipleActiveResultSets=true;User=SA;Password=Ch@ngeMe123;Integrated Security=false
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=False
      - CRYPTOCOMPARE_API_KEY=xxx
      - COINBASE_PASSPHRASE_KEY=changeme
      - COINBASE_API_KEY= changeme
    networks:
      - indexmanager
    ports: 
      - "4000:4100"
    restart: always
    
  indexmanager_client:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    build:
      context: ./..
      dockerfile: ./src/IndexManagerClient.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Consider changing this in Production
      - IndexManagerApiConfiguration__BaseUrl=https://localhost:4100
    networks:
      - indexmanager
    ports: 
      - "6000:6100"
    restart: always


  collector:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    #image: docker.pkg.github.com/trakx/trakx-tools/trakx-marketdata-collector:latest
    build:
      context: ./..
      dockerfile: ./src/Collector.Dockerfile
    environment:
      - ConnectionStrings__SqlServerConnection=Server=sqlserver;Database=IndiceRepository;Trusted_Connection=True;MultipleActiveResultSets=true;User=SA;Password=Ch@ngeMe123;Integrated Security=false
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=False
      - CRYPTOCOMPARE_API_KEY=xxx
      - PriceCacheConfiguration__CryptoCompareRestApiPollingPeriodMs=5678
      - PriceCacheConfiguration__RetryDbConnectionPeriodMs=1234
    depends_on:
      - marketdata_api
    links:
      - redis
      - sqlserver
    networks:
      - marketdata
    restart: always

  sqlserver:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - SA_PASSWORD=Ch@ngeMe123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - marketdata
      - indexmanager
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - marketdata
      - indexmanager
    restart: always

  proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    build:
      context:  ./nginx
      dockerfile: Dockerfile.local
    ports:
      - "80:80"
      - "443:443"
      - "4100:4100"
      - "5100:5100"
    networks:
      - marketdata      
      - indexmanager
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - marketdata_api
      - indexmanager_api
    restart: always

volumes:
  sqlvolume:

networks:
  marketdata:
    name: marketdata_network
    ipam:
      driver: default

  indexmanager:
    name: indexmanager_network
    ipam:
      driver: default